### ISSUE TITLE
issue in generating data

### ISSUE THREAD

**Issue by jarvis1200** [BB-Repos/BBpose#2]
Saving 'val' csv file to: /content/BBpose/bbpose/data/mpii/data/full/

Generating Tensorflow Records...
Traceback (most recent call last):
  File "BBpose/bbpose/main.py", line 290, in <module>
    main()
  File "BBpose/bbpose/main.py", line 277, in main
    generator.generate()
  File "/content/BBpose/bbpose/ingestion/ingest.py", line 120, in generate
    self._create_records(train_dataset, 'train')
  File "/content/BBpose/bbpose/ingestion/ingest.py", line 255, in _create_records
    record_num,
  File "/content/BBpose/bbpose/ingestion/ingest.py", line 274, in _write_to_record
    raw_image =  open(path, 'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: '/PATH/TO/IMG/DIR/015601864.jpg'

**Comment by vinayvp** [comment]
hello jarvis1200, you can edit the path in config.py, main.py and in utils.py, it worked for me
